kind: pipeline
type: docker
name: hello-world

platform:
  arch: arm64

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: say-hello
    image: busybox
    commands:
      - echo hello-world
